name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install HTML validator
        run: npm install --global html-validate

      - name: Validate HTML
        run: html-validate index.html

      - name: Install ESLint
        run: npm install --global eslint

      - name: Lint JavaScript
        run: eslint .